baseurl = "https://darren2013.github.io/"
#languageCode = "en-us"
languageCode = "zh-cn"
title = "Darren's Note"
# Copyright notice. This is displayer in the footer.
copyright = "&copy; Copyright (c) 2016 - 2025, DarrenDu; all rights reserved"

[params]
    # Social accounts. Link to these accounts are displayed in the header and
    # footer.
    #twitter = "Your Twitter username"
    github = "darren2013"
    #linkedin = "Your LinkedIn username"
    #googleplus = "Your Google+ user id"
    #facebook = "Your Facebook username"
    #stackoverflow = "Your Stackoverflow user id (number)"
    #keybase = "Your keybase.io username"
    #instagram = "Your Instagram username"
    # Disqus shortname
    #disqus = "Your disqus shortname"
    # Google Analytics API key.
    #ga_api_key = "Your Google Analytics tracking id"
    # Mixpanel API key.
    #mixpanel_api_key = "Your Mixpanel API key"
    author = "darren"
    #avatar = "/path/to/avatar"
    contact = "mailto:ddf168913@gmail.com"
    bio = "A java and Go enginer"
    # Short subtitle/tagline. This is displayed in the header.
    subtitle = "Short subtitle/tagline of your blog"
    themecolor = "#hexcolor" # Defines the tab color in Chrome for Android.

